packages:
- '.'
- location: './taffybar'
  extra-dep: true
# - location:
#     git: https://github.com/willdonnelly/dyre
#     commit: 11412752b483135e0c151ab90be17b217f837c4b
#   extra-dep: true
extra-deps:
- broadcast-chan-0.2.0.2 # from Ivan
- ConfigFile-1.1.4 # from Ivan
- dbus-1.2.1
- dbus-hslogger-0.1.0.1
- gi-cairo-connector-0.0.1 # from Ivan
- gi-cairo-render-0.0.1 # from Ivan
- gi-dbusmenu-0.4.6
- gi-dbusmenugtk3-0.4.7
- gi-gdk-3.0.21
- gi-gdkpixbuf-2.0.18
- gi-gdkx11-3.0.8
- gi-gio-2.0.16
- gi-glib-2.0.17
- gi-gtk-3.0.21
- gi-gtk-hs-0.3.6.1
- gi-pango-1.0.16
- gi-xlib-2.0.7
- gio-0.13.4.1
- gtk-sni-tray-0.1.6.0
- gtk-strut-0.1.3.0
- haskell-gi-0.22.6
- libxml-sax-0.7.5
- rate-limit-1.4.1
- spool-0.1
- status-notifier-item-0.3.0.3
- time-units-1.0.0
- X11-xft-0.3.1
- xml-helpers-1.0.0
resolver: lts-11.16
allow-newer: true
